### ISSUE TITLE
I am not from example.com

### ISSUE THREAD

**Issue by whit537** [concentricsky/badgr-server#14]
I just registered an account, and am seeing `example.com` in the verification email:

![screen shot 2015-07-27 at 9 30 29 pm](https://cloud.githubusercontent.com/assets/134455/8921652/caa1c4a8-34a6-11e5-9262-b53380c5db37.png)

**Comment by ottonomy** [comment]
Fixed on badgr.io. Thanks for reporting! (Though the only way you'll know this is fixed is if you sign up for a new account).

**Comment by whit537** [comment]
Thanks @ottonomy. However, I signed up for another account, and am still seeing `example.com`:

![screen shot 2015-07-29 at 7 31 45 am](https://cloud.githubusercontent.com/assets/134455/8956439/ff316c8c-35c3-11e5-9f3d-cd60edb20502.png)
